amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.5
    alpha2: 1.0
    alpha3: 1.0
    alpha4: 0.5
    # alpha5: 0.2
    map_type: occupancy
    first_map_only: true
    yaml_filename: "306_300_map_save.yaml"


bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - "nav2_compute_path_to_pose_bt_node"
    - "nav2_follow_path_bt_node"
    - "nav2_back_up_bt_node"
    - "nav2_spin_bt_node"
    - "nav2_wait_bt_node"
    - "nav2_clear_costmap_service_bt_node"
    - "nav2_is_stuck_condition_bt_node"
    - "nav2_goal_reached_condition_bt_node"
    - "nav2_initial_pose_received_condition_bt_node"
    - "nav2_reinitialize_global_localization_service_bt_node"
    - "nav2_pipeline_goal_updated_condition_bt_node"
    - "nav2_keepout_filter_bt_node"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      update_frequency: 1.0
      publish_frequency: 1.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      plugins: ["voxel_layer", "obstacle_layer", "inflation_layer"]
